movie_service/urls.py
from django.contrib import admin
from django.urls import path, include
from user_app import views as user_views
from rating_app import views as rating_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', rating_views.start_page, name='index_page'),
    path('users/', include('user_app.urls', namespace='users')),
    path('movies/', include('rating_app.urls', namespace='movies')),
    path('wishlist/', include('wishlist_app.urls', namespace='wishlists'))
]

user_app/urls.py
from django.urls import path
from .views import login_user, register_user, logout_user

app_name = 'user_app'

urlpatterns = [
    path('register/', register_user, name='register_page'),
    path('login/', login_user, name='login_page'),
    path('logout/', logout_user, name='logout'),
]

user_app/models.py
from django.db import models

# Create your models here.

user_app/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='', max_length=50, widget=forms.TextInput(attrs={'class': "form-field",
                                                                                      'placeholder': "Username"}))

    email = forms.EmailField(label='', max_length=100, widget=forms.TextInput(attrs={'class': "form-field",
                                                                                     'placeholder': "Email"}))

    password1 = forms.CharField(label='', widget=(forms.PasswordInput(attrs={'class': "form-field",
                                                                             'placeholder': "Password"})))

    password2 = forms.CharField(label='', widget=(forms.PasswordInput(attrs={'class': "form-field",
                                                                             'placeholder': "Password Confirmation"})))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "password1", "password2")
        help_texts = {
            'password': None
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match.")
        return cd['password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='', max_length=50, widget=forms.TextInput(attrs={'class': "form-field",
                                                                                      'placeholder': "Login"}))

    password = forms.CharField(label='', widget=(forms.PasswordInput(attrs={'class': "form-field",
                                                                            'placeholder': "Password"})))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "password")
        help_texts = {
            'password': None
        }

user_app/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import auth
from .forms import RegisterForm, LoginForm


# Create your views here.
def register_user(request) -> HttpResponseRedirect | HttpResponse:
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user_app:login_page'))
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'register_form': form})


def login_user(request) -> HttpResponseRedirect | HttpResponse:
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username: str = request.POST['username']
            password: str = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index_page'))
    else:
        form = LoginForm()
    return render(request, 'login.html', {'login_form': form})


def logout_user(request) -> HttpResponseRedirect:
    auth.logout(request)
    return HttpResponseRedirect(reverse('index_page'))

user_app/templates/user_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'user_app/css/style.css' %}">
    <title>Movier</title>
</head>
<body>

{% block welcome_page %}
{% endblock %}

{% block login_page %}
{% endblock %}

{% block register_page %}
{% endblock %}

{% block rating_page %}
{% endblock %}

<script src="{% static 'js/script.js'%}"></script>
</body>
</html>

user_app/templates/user_app/login.html
{% extends 'user_app/base.html' %}
{% block login_page %}
<main class="main">
    <div class="wrapper">
        <div class="container">
            <div class="title">
                <h2>Log in to your account</h2>
            </div>
            <form action="{% url 'user_app:login_page' %}" method="POST">
                {% csrf_token %}
                {{ login_form }}
                <button type="submit" class="form-btn">
                    <div>Sign in</div>
                </button>
            </form>
            <span>don't have account yet, <a class="account" href="{% url 'user_app:register_page' %}">click here</a></span>
        </div>
    </div>
</main>
{% endblock %}

user_app/templates/user_app/register.html
{% extends 'user_app/base.html' %}
{% block register_page %}
<main class="main">
    <div class="wrapper">
        <div class="container">
            <div class="title">
                <h2>Create account</h2>
            </div>
            <form action="{% url 'user_app:register_page' %}" method="POST">
                {% csrf_token%}
                {{ register_form }}
                <button type="submit" class="form-btn">
                    <div>Sign up</div>
                </button>
            </form>
            <span>already have an account, <a class="account" href="{% url 'user_app:login_page' %}">click here</a></span>
        </div>
    </div>
</main>
{% endblock %}