movie_service/urls.py
from django.contrib import admin
from django.urls import path, include
from user_app import views as user_views
from rating_app import views as rating_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', rating_views.start_page, name='index_page'),
    path('users/', include('user_app.urls', namespace='users')),
    path('movies/', include('rating_app.urls', namespace='movies')),
    path('wishlist/', include('wishlist_app.urls', namespace='wishlists'))
]

rating_app/urls.py
from django.urls import path
from .views import show_rating, create_rating, choose_movie

app_name = 'rating_app'

urlpatterns = [
    path('rating', show_rating, name='rating_page'),
    path('rating/create', create_rating, name='create_page'),
    path('rating/choose', choose_movie, name='choose_page')
]

user_app/urls.py
from django.urls import path
from .views import login_user, register_user, logout_user

app_name = 'user_app'

urlpatterns = [
    path('register/', register_user, name='register_page'),
    path('login/', login_user, name='login_page'),
    path('logout/', logout_user, name='logout'),
]

rating_app/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50, verbose_name='Title')

    year = models.CharField(max_length=4, verbose_name='Year')

    link = models.CharField(max_length=150, verbose_name='Link')

    kp_rating = models.FloatField(verbose_name='KP-Rating')

    rating = models.FloatField(verbose_name='Your rating')

    movie_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='user'
    )

    def __str__(self) -> str:
        return f'{self.title}'

rating_app/forms.py
from django import forms


class CreationForm(forms.Form):
    title = forms.CharField(label='', max_length=100, widget=forms.TextInput(attrs={'class': "form-field",
                                                                                    'placeholder': "Title"}))

    rating = forms.IntegerField(label='', widget=forms.TextInput(attrs={'class': "rating-field",
                                                                        'type': 'range',
                                                                        'min': '0',
                                                                        'max': '10',
                                                                        'step': '0.5',
                                                                        'value': '0'}))

rating_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .decorators import rate_film_required

from .models import Movie
from .forms import CreationForm
from .utils import get_films_data, get_film_by_id, FILM, filter_movie


# Create your views here.
def start_page(request) -> HttpResponse:
    return render(request, 'index.html')


@login_required(login_url='users:login_page')
def show_rating(request) -> HttpResponse | HttpResponseRedirect:
    if request.POST.get('film'):
        movie_id: int = int(request.POST['film'])
        new_rating: float = float(request.POST['new_rating'])
        Movie.objects.filter(pk=movie_id).update(rating=new_rating)
        return HttpResponseRedirect(reverse('movies:rating_page'))
    else:
        order_type: str = filter_movie(request)
        user: str = request.user
        movies = Movie.objects.filter(movie_user=user).order_by(order_type)
    return render(request, 'marks.html', {'movies': movies})


@login_required(login_url='users:login_page')
def create_rating(request) -> HttpResponse:
    if request.POST.get('title'):
        title: str = request.POST['title']
        rating: str = request.POST['rating']
        return HttpResponseRedirect(reverse('movies:choose_page') + f'?title={title}&rating={rating}')
    form = CreationForm()
    return render(request, 'create_mark.html', {'form': form})


@rate_film_required
@login_required(login_url='users:login_page')
def choose_movie(request) -> HttpResponse:
    if request.POST.get('film'):
        movie_id: int = int(request.POST.get('film'))
        movie_data: FILM = get_film_by_id(movie_id)
        user: str = request.user
        rating: float = float(request.POST.get('rating'))
        Movie.objects.create(title=movie_data.ru_name, year=movie_data.year, link=movie_data.kp_url,
                             kp_rating=movie_data.kp_rate,
                             rating=rating, movie_user=user)
        return HttpResponseRedirect(reverse('index_page'))
    else:
        rating: str = request.GET.get('rating')
        title: str = request.GET.get('title')
        films_data: list = get_films_data(title)
    return render(request, 'choose_movie.html', {'films_data': films_data,
                                                 'rating': rating})

rating_app/templates/rating_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'rating_app/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <title>Movier</title>
</head>
<body>

{% block rating_page %}
{% endblock %}

{% block create_page %}
{% endblock %}

<script src="{% static 'js/script.js'%}"></script>
</body>
</html>

rating_app/templates/rating_app/choose_movie.html
{% extends 'rating_app/base.html' %}
{% load static %}
{% block rating_page %}
<section class="wrapper">
    <h1 class="movie-header">Choose right movie!</h1>
    <a class="go_back" href="{% url 'movies:rating_page' %}">Go back!</a>
    <form class="choose-form" action="{% url 'movies:choose_page' %}" method="post">
        {% csrf_token %}
        <div class="main-table">
            <div class="tbl-header">
                <table>
                    <thead>
                        <tr>
                            <th>poster</th>
                            <th>film</th>
                            <th>year</th>
                            <th>link</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="tbl-content">
                <table>
                    <tbody>
                    {% for item in films_data %}
                        <tr>
                            <td>
                                <img src="{{item.poster_preview}}" alt="poster">
                            </td>
                            <td>
                                <input style="display: none;" type="text" name="rating" value="{{rating}}">
                                <input type="radio" name="film" value="{{item.kp_id}}">
                                <label for="film">{{item.ru_name}}</label>
                            </td>
                            <td>{{item.year}}</td>
                            <td><a class="movie-link" href="{{item.kp_url}}">Click</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="update-btn">
            <button type="submit">Choose movie</button>
        </div>
    </form>
</section>
{% endblock %}

rating_app/templates/rating_app/create_mark.html
{% extends 'rating_app/base.html' %}
{% load static %}
{% block create_page %}
<section class="wrapper">
    <h1 class="movie-header">Rate new film!</h1>
    <form class="create_rating" action="{% url 'movies:create_page' %}" method="post">
        {% csrf_token %}
        <div class="range-container">
            {{form}}
            <div id="h4-container">
                <div id="h4-subcontainer">
                    <h4>0
                        <span></span>
                    </h4>
                </div>
            </div>
        </div>
        <button type="submit">Оценить</button>
    </form>
</section>
{% endblock %}

rating_app/templates/rating_app/marks.html
{% extends 'rating_app/base.html' %}
{% load static %}
{% block rating_page %}
<section class="wrapper">
    <h1 class="movie-header">Rating</h1>
    <div class="movie-menu">
        <form action="{% url 'movies:rating_page' %}" method="GET" class="sorting-form">
            <span>Sorting by: </span>
            <div>
                <ul class="sorting-menu">
                    <li>[ASC]</li>
                    <li><input type="submit" name="title" value="title" class="sort-item"></li>
                    <li><input type="submit" name="year" value="year" class="sort-item"></li>
                    <li><input type="submit" name="rating" value="rating" class="sort-item"></li>
                </ul>
                <ul class="sorting-menu">
                    <li>[DESC]</li>
                    <li><input type="submit" name="-title" value="title" class="sort-item"></li>
                    <li><input type="submit" name="-year" value="year" class="sort-item"></li>
                    <li><input type="submit" name="-rating" value="rating" class="sort-item"></li>
                </ul>
            </div>
        </form>
        <div>
            <a class="go_back" href="{% url 'index_page' %}">Go back!</a>
            <a class="rate_new" href="{% url 'movies:create_page' %}">Rate new film!</a>
        </div>
    </div>
    <form action="{% url 'movies:rating_page' %}" method="post">
        {% csrf_token %}
        <div class="main-table">
            <div class="tbl-header">
                <table>
                    <thead>
                        <tr>
                            <th>film</th>
                            <th>year</th>
                            <th>link</th>
                            <th>rating</th>
                            <th>Your rating</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="tbl-content">
                <table>
                    <tbody>
                    {% for item in movies %}
                        <tr>
                            <td>
                                <input class="" type="radio" name="film" value="{{item.pk}}">
                                <label for="film">{{item.title}}</label>
                            </td>
                            <td>{{item.year}}</td>
                            <td><a class="movie-link" href="{{item.link}}">Click</a></td>
                            <td>{{item.kp_rating}}</td>
                            <td>{{item.rating}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="update-btn">
            <div class="update-rating">
                <h3>Choose new rating</h3>
                <input name="new_rating" type="range" value="0" min="0" max="10" step="0.5">
                <div id="h4-container">
                    <div id="h4-subcontainer">
                        <h4>0
                            <span></span>
                        </h4>
                    </div>
                </div>
            </div>
            <button type="submit">Update rating</button>
        </div>
    </form>
</section>
{% endblock %}